---
- hosts: aws_ec2
  become: yes
  connection: ssh
  user: ec2-user

  vars:
    ansible_ssh_private_key_file: "/etc/ansible/osaka-reg.pem"
    ansible_ssh_user: "ec2-user"

  tasks:
    - name: install web server
      yum: name=httpd state=present

    - name: start webserver
      service: name=httpd state=started

    - name: install git
      yum: name=git state=present

    - name: get the source code from github
      git:
        repo: "https://github.com/thisismanjurocks/monolithicproject.git"
        dest: /var/www/html/
        version: frontend
